apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jumpwire-setup
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jumpwire-setup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jumpwire-setup
subjects:
- kind: ServiceAccount
  name: jumpwire-setup
roleRef:
  kind: Role
  name: jumpwire-setup
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: jumpwire-initial-setup
  labels:
    app: jumpwire
    jumpwire.ai/application: setup
spec:
  template:
    spec:
      containers:
        - name: setup
          image: bitnami/kubectl:1.21
          command:
            - bash
          args:
            - -c
            - >-
              tr -dc A-Za-z0-9 </dev/urandom | head -c 30 > /tmp/cookie &&
              kubectl create secret generic jumpwire-secret --from-file=cookie=/tmp/cookie
      restartPolicy: OnFailure
      serviceAccount: jumpwire-setup
