apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jumpwire
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jumpwire

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jumpwire
subjects:
- kind: ServiceAccount
  name: jumpwire
roleRef:
  kind: Role
  name: jumpwire
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpwire
  labels:
    app: jumpwire
    jumpwire.ai/application: jumpwire
spec:
  replicas: 2
  selector:
    matchLabels:
      jumpwire.ai/application: jumpwire
  template:
    metadata:
      labels:
        app: jumpwire
        jumpwire.ai/application: jumpwire
    spec:
      serviceAccountName: jumpwire
      containers:
        - image: jumpwire/jumpwire:0.1.0
          name: jumpwire
          env:
            - name: JUMPWIRE_CLOUD
              value: kubernetes
            - name: JUMPWIRE_NODE
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JUMPWIRE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: jumpwire-secret
                  key: cookie
          ports:
            - containerPort: 4369
              name: beam
            - containerPort: 4000
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: jumpwire
  labels:
    app: jumpwire
    jumpwire.ai/application: jumpwire
spec:
  ports:
    - port: 4369
      targetPort: beam
      protocol: TCP
      name: beam
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    jumpwire.ai/application: jumpwire
